#!/bin/sh

################################################################################
#
#  firefox-install
#
#  Install/Update Mozilla Firefox for current user. This also works as a version manager.
#
#  Homepage: https://www.firefox.com/
#
#  Usage:
#    firefox-install <version>
#
#  Example:
#    firefox-install 147.0.4
#    firefox-install v147.0.4
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

set -ex

# Application info
PROGRAM_ID="firefox"
PROGRAM_EXEC="Firefox.app"

# Shared library
CTXDIR="$(cd "$(dirname "$0")" && pwd)"
. "${CTXDIR}/shared/install-common.sh"

# Prepare environment
normalize_install_version "$1"
init_install_env_desktop "${PROGRAM_ID}" "${INSTALL_VERSION}"

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	BIN_ARCH_URI_AMD64="https://ftp.mozilla.org/pub/firefox/releases/${INSTALL_VERSION}/mac/en-US/Firefox%20${INSTALL_VERSION}.dmg"
	BIN_ARCH_URI_ARM64="https://ftp.mozilla.org/pub/firefox/releases/${INSTALL_VERSION}/mac/en-US/Firefox%20${INSTALL_VERSION}.dmg"
	BIN_ARCH_TMP_FILE="${TEMP_TARGET}.tar.gz"
	download_uri_per_arch "${BIN_ARCH_URI_AMD64}" "${BIN_ARCH_URI_ARM64}" "${BIN_ARCH_TMP_FILE}"
	create_dir "${TEMP_TARGET}"
	extract_archive "${BIN_ARCH_TMP_FILE}" "dmg" "${TEMP_TARGET}"
	remove_item "${BIN_ARCH_TMP_FILE}"
	move_item_overwrite "${TEMP_TARGET}" "${INSTALL_TARGET}"
	remove_item "${TEMP_TARGET}"
fi

# Finalize install
copy_item_overwrite "${INSTALL_TARGET}" "${ACTIVE_TARGET}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC}" "${DESKTOP_ROOT}/${PROGRAM_EXEC}"
