#!/bin/sh

################################################################################
#
#  hugo-install
#
#  Install/Update Hugo for current user. This also works as a version manager.
#  If version is not specified, the latest version will be installed.
#
#  Homepage: https://gohugo.io/
#
#  Usage:
#    hugo-install [<version>]
#
#  Example:
#    hugo-install
#    hugo-install 0.170.1
#    hugo-install v0.170.1
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

set -ex

# Application info
GITHUB_OWNER="gohugoio"
GITHUB_REPO="hugo"
PROGRAM_ID="hugo"
PROGRAM_EXEC="hugo"

# Shared library
CTXDIR="$(cd "$(dirname "$0")" && pwd)"
. "${CTXDIR}/shared/install-common.sh"

# Prepare environment
get_install_version_from_github "${GITHUB_OWNER}" "${GITHUB_REPO}" "$1"
init_install_env "${PROGRAM_ID}" "${INSTALL_VERSION}"

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	BIN_ARCH_URI_AMD64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/hugo_extended_withdeploy_${INSTALL_VERSION}_darwin-universal.pkg"
	BIN_ARCH_URI_ARM64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/hugo_extended_withdeploy_${INSTALL_VERSION}_darwin-universal.pkg"
	BIN_ARCH_TMP_FILE="${TEMP_TARGET}.pkg"
	download_uri_per_arch "${BIN_ARCH_URI_AMD64}" "${BIN_ARCH_URI_ARM64}" "${BIN_ARCH_TMP_FILE}"
	create_dir "${TEMP_TARGET}"
	extract_archive "${BIN_ARCH_TMP_FILE}" "pkg" "${TEMP_TARGET}"
	remove_item "${BIN_ARCH_TMP_FILE}"
	move_item "${TEMP_TARGET}/Payload" "${INSTALL_TARGET}"
	remove_item "${TEMP_TARGET}"
fi

# Finalize install
symlink_item_overwrite "${INSTALL_TARGET}" "${ACTIVE_TARGET}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC}" "${SYSTEM_BIN_ROOT}/${PROGRAM_ID}"
