#!/bin/sh

################################################################################
#
#  kitty-install
#
#  Install/Update Kitty for current user. This also works as a version manager.
#  If version is not specified, the latest version will be installed.
#
#  Homepage: https://sw.kovidgoyal.net/kitty/
#
#  Usage:
#    kitty-install [<version>]
#
#  Example:
#    kitty-install
#    kitty-install 0.47.0
#    kitty-install v0.47.0
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

set -ex

# Application info
GITHUB_OWNER="kovidgoyal"
GITHUB_REPO="kitty"
PROGRAM_ID="kitty"
PROGRAM_EXEC="Kitty.app"

# Shared library
CTXDIR="$(cd "$(dirname "$0")" && pwd)"
. "${CTXDIR}/shared/install-common.sh"

# Prepare environment
get_install_version_from_github "${GITHUB_OWNER}" "${GITHUB_REPO}" "$1"
init_install_env_desktop "${PROGRAM_ID}" "${INSTALL_VERSION}"

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	BIN_ARCH_URI_AMD64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/kitty-${INSTALL_VERSION}.dmg"
	BIN_ARCH_URI_ARM64="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/download/v${INSTALL_VERSION}/kitty-${INSTALL_VERSION}.dmg"
	BIN_ARCH_TMP_FILE="${TEMP_TARGET}.dmg"
	download_uri_per_arch "${BIN_ARCH_URI_AMD64}" "${BIN_ARCH_URI_ARM64}" "${BIN_ARCH_TMP_FILE}"
	create_dir "${TEMP_TARGET}"
	extract_archive "${BIN_ARCH_TMP_FILE}" "dmg" "${TEMP_TARGET}"
	remove_item "${BIN_ARCH_TMP_FILE}"
	move_item_overwrite "${TEMP_TARGET}" "${INSTALL_TARGET}"
	remove_item "${TEMP_TARGET}"
fi

# Finalize install
symlink_item_overwrite "${INSTALL_TARGET}" "${ACTIVE_TARGET}"
symlink_item_overwrite "${ACTIVE_TARGET}/${PROGRAM_EXEC}" "${DESKTOP_ROOT}/${PROGRAM_EXEC}"
