#!/bin/sh

################################################################################
#
#  waterfox-install
#
#  Install/Update Waterfox for current user. This also works as a version manager.
#  If version is not specified, the latest version will be installed.
#
#  Homepage: https://www.waterfox.com/
#
#  Usage:
#    waterfox-install [<version>]
#
#  Example:
#    waterfox-install
#    waterfox-install 6.7.7
#    waterfox-install v6.7.7
#
#  MIT License.
#  Copyright (C) 2025 Nguyen Nhat Tung.
#
################################################################################

# Application info
GITHUB_OWNER="BrowserWorks"
GITHUB_REPO="waterfox"
PROGRAM_ID="waterfox"
PROGRAM_EXEC="Waterfox.app"

set -ex

# Determine version to install
if [ -z "$1" ]; then
	LATEST_VERSION="$(curl https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/releases/latest | jq -r .tag_name)"
else
	LATEST_VERSION="$1"
fi
LATEST_VERSION="${LATEST_VERSION#v}"

# Installation environment
USERID="$(id -u)"
ARCH="$(uname -m)"
if [ "${USERID}" -eq 0 ]; then
	INSTALL_ROOT="/usr/local/share/${PROGRAM_ID}"
	SYSTEM_BIN_ROOT="/usr/local/bin"
	DESKTOP_BIN_ROOT="/Applications"
else
	INSTALL_ROOT="${HOME}/.local/share/${PROGRAM_ID}"
	SYSTEM_BIN_ROOT="${HOME}/.local/bin"
	DESKTOP_BIN_ROOT="${HOME}/Desktop"
fi
INSTALL_TARGET="${INSTALL_ROOT}/${PROGRAM_ID}-v${LATEST_VERSION}"
ACTIVE_TARGET="${INSTALL_ROOT}/active-release"

if [ ! -d "${INSTALL_ROOT}" ]; then
	mkdir -p "${INSTALL_ROOT}"
fi
if [ ! -d "${SYSTEM_BIN_ROOT}" ]; then
	mkdir -p "${SYSTEM_BIN_ROOT}"
fi

# Download and install binaries
if [ ! -d "${INSTALL_TARGET}" ]; then
	BIN_ARCH_URI_AMD64="https://cdn.waterfox.com/waterfox/releases/${LATEST_VERSION}/Darwin_x86_64-aarch64/Waterfox%20${LATEST_VERSION}.dmg"
	BIN_ARCH_URI_ARM64="https://cdn.waterfox.com/waterfox/releases/${LATEST_VERSION}/Darwin_x86_64-aarch64/Waterfox%20${LATEST_VERSION}.dmg"
	BIN_ARCH_TMP_FILE="/tmp/${PROGRAM_ID}-v${LATEST_VERSION}.dmg"

	if [ "${ARCH}" = "x86_64" ] || [ "${ARCH}" = "amd64" ]; then
		curl -fSL "${BIN_ARCH_URI_AMD64}" -o "${BIN_ARCH_TMP_FILE}"
	elif [ "${ARCH}" = "aarch64" ] || [ "${ARCH}" = "arm64" ]; then
		curl -fSL "${BIN_ARCH_URI_ARM64}" -o "${BIN_ARCH_TMP_FILE}"
	else
		echo "Unsupported architecture: ${ARCH}"
		exit 1
	fi

	TEMP_TARGET="/tmp/${PROGRAM_ID}-v${LATEST_VERSION}"
	mkdir "${TEMP_TARGET}"
	MOUNT_POINT="/Volumes/Waterfox Install"
	hdiutil attach -mountpoint "${MOUNT_POINT}" "${BIN_ARCH_TMP_FILE}"
	cp -r -P "${MOUNT_POINT}/${PROGRAM_EXEC}" "${TEMP_TARGET}"
	hdiutil detach "${MOUNT_POINT}"
	xattr -cr "${TEMP_TARGET}"
	rm "${BIN_ARCH_TMP_FILE}"
	mv "${TEMP_TARGET}" "${INSTALL_TARGET}"
	if [ -d "${TEMP_TARGET}" ]; then
		rm -r "${TEMP_TARGET}"
	fi
fi

# Set active release
if [ -f "${ACTIVE_TARGET}" ] || [ -d "${ACTIVE_TARGET}" ] || [ -L "${ACTIVE_TARGET}" ]; then
	rm -r "${ACTIVE_TARGET}"
fi
cp -r -P "${INSTALL_TARGET}" "${ACTIVE_TARGET}"

# Create symlink for quick access
ACTIVE_TARGET_BIN="${ACTIVE_TARGET}/${PROGRAM_EXEC}"
SYSTEM_BIN_TARGET_BIN="${SYSTEM_BIN_ROOT}/${PROGRAM_EXEC}"
if [ -f "${ACTIVE_TARGET_BIN}" ] || [ -d "${ACTIVE_TARGET_BIN}" ]; then
	if [ -f "${SYSTEM_BIN_TARGET_BIN}" ] || [ -d "${SYSTEM_BIN_TARGET_BIN}" ] || [ -L "${SYSTEM_BIN_TARGET_BIN}" ]; then
		rm -r "${SYSTEM_BIN_TARGET_BIN}"
	fi
	ln -s "${ACTIVE_TARGET_BIN}" "${SYSTEM_BIN_TARGET_BIN}"
fi

# Create desktop symlink for quick access
ACTIVE_TARGET_BIN="${ACTIVE_TARGET}/${PROGRAM_EXEC}"
DESKTOP_BIN_TARGET_BIN="${DESKTOP_BIN_ROOT}/${PROGRAM_EXEC}"
if [ -f "${ACTIVE_TARGET_BIN}" ] || [ -d "${ACTIVE_TARGET_BIN}" ]; then
	if [ -f "${DESKTOP_BIN_TARGET_BIN}" ] || [ -d "${DESKTOP_BIN_TARGET_BIN}" ] || [ -L "${DESKTOP_BIN_TARGET_BIN}" ]; then
		rm -r "${DESKTOP_BIN_TARGET_BIN}"
	fi
	ln -s "${ACTIVE_TARGET_BIN}" "${DESKTOP_BIN_TARGET_BIN}"
fi
